#!/bin/bash
# Unity Package Verification Script
# This script checks if Unity packages are correctly installed and identifies issues

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$SCRIPT_DIR"

echo "==========================================="
echo "Unity Package Verification Script"
echo "==========================================="
echo ""
echo "Checking Unity package installation..."
echo "Project directory: $PROJECT_DIR"
echo ""

# Check if manifest.json exists
if [ ! -f "$PROJECT_DIR/Packages/manifest.json" ]; then
    echo "❌ ERROR: Packages/manifest.json not found!"
    exit 1
fi

# Check Unity version
echo "[1/5] Checking Unity version..."
if [ -f "$PROJECT_DIR/ProjectSettings/ProjectVersion.txt" ]; then
    UNITY_VERSION=$(grep "m_EditorVersion:" "$PROJECT_DIR/ProjectSettings/ProjectVersion.txt" | cut -d' ' -f2)
    echo "✓ Unity version: $UNITY_VERSION"
    
    if [[ "$UNITY_VERSION" == 6000.* ]]; then
        echo "✓ Unity 6 LTS detected"
    else
        echo "⚠️  WARNING: This project is configured for Unity 6 LTS"
        echo "   Your version: $UNITY_VERSION"
    fi
else
    echo "⚠️  Cannot detect Unity version (ProjectVersion.txt not found)"
fi

# Check for tilemap.extras version in manifest
echo ""
echo "[2/5] Checking tilemap.extras package version in manifest..."
MANIFEST_VERSION=$(grep -o '"com.unity.2d.tilemap.extras": "[^"]*"' "$PROJECT_DIR/Packages/manifest.json" | cut -d'"' -f4)
if [ -n "$MANIFEST_VERSION" ]; then
    echo "✓ Manifest version: $MANIFEST_VERSION"
    
    if [ "$MANIFEST_VERSION" == "6.0.1" ]; then
        echo "✓ Correct version for Unity 6 LTS"
    else
        echo "⚠️  WARNING: Expected version 6.0.1 for Unity 6 LTS"
        echo "   Found: $MANIFEST_VERSION"
    fi
else
    echo "❌ ERROR: com.unity.2d.tilemap.extras not found in manifest.json"
    exit 1
fi

# Check packages-lock.json
echo ""
echo "[3/5] Checking packages-lock.json..."
if [ -f "$PROJECT_DIR/Packages/packages-lock.json" ]; then
    LOCK_VERSION=$(grep -A 1 '"com.unity.2d.tilemap.extras"' "$PROJECT_DIR/Packages/packages-lock.json" | grep '"version":' | cut -d'"' -f4)
    if [ -n "$LOCK_VERSION" ]; then
        echo "✓ Lock file version: $LOCK_VERSION"
        
        if [ "$LOCK_VERSION" == "$MANIFEST_VERSION" ]; then
            echo "✓ Lock file matches manifest"
        else
            echo "⚠️  WARNING: Version mismatch between manifest and lock file!"
            echo "   Manifest: $MANIFEST_VERSION"
            echo "   Lock:     $LOCK_VERSION"
            echo "   Solution: Run cleanup script to regenerate lock file"
        fi
    else
        echo "⚠️  Cannot find tilemap.extras version in lock file"
    fi
else
    echo "ℹ packages-lock.json does not exist (will be regenerated by Unity)"
fi

# Check Library/PackageCache
echo ""
echo "[4/5] Checking Library/PackageCache..."
if [ -d "$PROJECT_DIR/Library/PackageCache" ]; then
    # Find tilemap.extras package in cache
    CACHED_PACKAGE=$(find "$PROJECT_DIR/Library/PackageCache" -maxdepth 1 -type d -name "com.unity.2d.tilemap.extras@*" 2>/dev/null | head -1)
    
    if [ -n "$CACHED_PACKAGE" ]; then
        CACHED_VERSION=$(basename "$CACHED_PACKAGE" | sed 's/com.unity.2d.tilemap.extras@//')
        echo "✓ Found cached package: $CACHED_VERSION"
        
        # Check if TileTemplate files exist (they shouldn't in 6.0.1)
        if [ -f "$CACHED_PACKAGE/Editor/Tiles/AutoTile/AutoTileTemplate.cs" ]; then
            echo ""
            echo "⚠️  Checking for TileTemplate references..."
            if grep -q "TileTemplate" "$CACHED_PACKAGE/Editor/Tiles/AutoTile/AutoTileTemplate.cs" 2>/dev/null; then
                echo "❌ ERROR: Old cached package detected!"
                echo "   The cached package contains deprecated TileTemplate references"
                echo "   This is the source of your compilation errors"
                echo ""
                echo "   SOLUTION: Run the advanced-cleanup script:"
                echo "   - On Windows: .\\advanced-cleanup.ps1"
                echo "   - On macOS/Linux: ./advanced-cleanup.sh"
            else
                echo "✓ No TileTemplate references found"
            fi
        else
            echo "✓ Package appears correct (no AutoTileTemplate.cs found as expected)"
        fi
    else
        echo "⚠️  tilemap.extras not found in PackageCache"
        echo "   Unity hasn't downloaded packages yet"
        echo "   Solution: Open project in Unity to download packages"
    fi
else
    echo "ℹ Library/PackageCache does not exist"
    echo "   This is normal for a fresh clone"
    echo "   Unity will create it when you open the project"
fi

# Summary
echo ""
echo "[5/5] Summary and Recommendations"
echo "=========================================="

# Determine if there are issues
ISSUES_FOUND=false

if [ -d "$PROJECT_DIR/Library/PackageCache" ]; then
    CACHED_PACKAGE=$(find "$PROJECT_DIR/Library/PackageCache" -maxdepth 1 -type d -name "com.unity.2d.tilemap.extras@*" 2>/dev/null | head -1)
    if [ -n "$CACHED_PACKAGE" ] && [ -f "$CACHED_PACKAGE/Editor/Tiles/AutoTile/AutoTileTemplate.cs" ]; then
        if grep -q "TileTemplate" "$CACHED_PACKAGE/Editor/Tiles/AutoTile/AutoTileTemplate.cs" 2>/dev/null; then
            ISSUES_FOUND=true
        fi
    fi
fi

if [ "$ISSUES_FOUND" = true ]; then
    echo "❌ ISSUES DETECTED"
    echo ""
    echo "Your Unity package cache contains old, incompatible files."
    echo "This is causing the TileTemplate compilation errors."
    echo ""
    echo "Recommended action:"
    echo "  1. Close Unity completely"
    echo "  2. Run the advanced cleanup script:"
    echo "     - Windows: .\\advanced-cleanup.ps1"
    echo "     - macOS/Linux: ./advanced-cleanup.sh"
    echo "  3. Reopen the project in Unity"
    echo ""
else
    echo "✓ NO ISSUES DETECTED"
    echo ""
    echo "Package configuration appears correct."
    echo ""
    if [ ! -d "$PROJECT_DIR/Library" ]; then
        echo "Next step: Open the project in Unity to generate the Library folder"
    else
        echo "If you're still experiencing errors:"
        echo "  1. Check the Unity Console for specific error messages"
        echo "  2. Try running the advanced-cleanup script"
        echo "  3. See TROUBLESHOOTING.md for more solutions"
    fi
fi

echo ""
