# Unity Package Verification Script (PowerShell)
# This script checks if Unity packages are correctly installed and identifies issues

$ErrorActionPreference = "Stop"

$ProjectDir = $PSScriptRoot

Write-Host "==========================================="
Write-Host "Unity Package Verification Script"
Write-Host "==========================================="
Write-Host ""
Write-Host "Checking Unity package installation..."
Write-Host "Project directory: $ProjectDir"
Write-Host ""

# Check if manifest.json exists
$manifestPath = Join-Path $ProjectDir "Packages\manifest.json"
if (-not (Test-Path $manifestPath)) {
    Write-Host "❌ ERROR: Packages\manifest.json not found!"
    exit 1
}

# Check Unity version
Write-Host "[1/5] Checking Unity version..."
$versionPath = Join-Path $ProjectDir "ProjectSettings\ProjectVersion.txt"
if (Test-Path $versionPath) {
    $versionContent = Get-Content $versionPath
    $unityVersion = ($versionContent | Select-String "m_EditorVersion:").ToString().Split(' ')[1]
    Write-Host "✓ Unity version: $unityVersion"
    
    if ($unityVersion -like "6000.*") {
        Write-Host "✓ Unity 6 LTS detected"
    } else {
        Write-Host "⚠️  WARNING: This project is configured for Unity 6 LTS"
        Write-Host "   Your version: $unityVersion"
    }
} else {
    Write-Host "⚠️  Cannot detect Unity version (ProjectVersion.txt not found)"
}

# Check for tilemap.extras version in manifest
Write-Host ""
Write-Host "[2/5] Checking tilemap.extras package version in manifest..."
$manifestContent = Get-Content $manifestPath -Raw
if ($manifestContent -match '"com.unity.2d.tilemap.extras":\s*"([^"]+)"') {
    $manifestVersion = $matches[1]
    Write-Host "✓ Manifest version: $manifestVersion"
    
    if ($manifestVersion -eq "6.0.1") {
        Write-Host "✓ Correct version for Unity 6 LTS"
    } else {
        Write-Host "⚠️  WARNING: Expected version 6.0.1 for Unity 6 LTS"
        Write-Host "   Found: $manifestVersion"
    }
} else {
    Write-Host "❌ ERROR: com.unity.2d.tilemap.extras not found in manifest.json"
    exit 1
}

# Check packages-lock.json
Write-Host ""
Write-Host "[3/5] Checking packages-lock.json..."
$lockPath = Join-Path $ProjectDir "Packages\packages-lock.json"
if (Test-Path $lockPath) {
    $lockContent = Get-Content $lockPath -Raw
    if ($lockContent -match '"com.unity.2d.tilemap.extras":\s*\{[^}]*"version":\s*"([^"]+)"') {
        $lockVersion = $matches[1]
        Write-Host "✓ Lock file version: $lockVersion"
        
        if ($lockVersion -eq $manifestVersion) {
            Write-Host "✓ Lock file matches manifest"
        } else {
            Write-Host "⚠️  WARNING: Version mismatch between manifest and lock file!"
            Write-Host "   Manifest: $manifestVersion"
            Write-Host "   Lock:     $lockVersion"
            Write-Host "   Solution: Run cleanup script to regenerate lock file"
        }
    } else {
        Write-Host "⚠️  Cannot find tilemap.extras version in lock file"
    }
} else {
    Write-Host "ℹ packages-lock.json does not exist (will be regenerated by Unity)"
}

# Check Library/PackageCache
Write-Host ""
Write-Host "[4/5] Checking Library\PackageCache..."
$packageCachePath = Join-Path $ProjectDir "Library\PackageCache"
if (Test-Path $packageCachePath) {
    # Find tilemap.extras package in cache
    $cachedPackage = Get-ChildItem $packageCachePath -Directory -Filter "com.unity.2d.tilemap.extras@*" | Select-Object -First 1
    
    if ($cachedPackage) {
        $cachedVersion = $cachedPackage.Name -replace "com.unity.2d.tilemap.extras@", ""
        Write-Host "✓ Found cached package: $cachedVersion"
        
        # Check if TileTemplate files exist (they shouldn't in 6.0.1)
        $autoTilePath = Join-Path $cachedPackage.FullName "Editor\Tiles\AutoTile\AutoTileTemplate.cs"
        if (Test-Path $autoTilePath) {
            Write-Host ""
            Write-Host "⚠️  Checking for TileTemplate references..."
            $fileContent = Get-Content $autoTilePath -Raw
            if ($fileContent -match "TileTemplate") {
                Write-Host "❌ ERROR: Old cached package detected!"
                Write-Host "   The cached package contains deprecated TileTemplate references"
                Write-Host "   This is the source of your compilation errors"
                Write-Host ""
                Write-Host "   SOLUTION: Run the advanced-cleanup script:"
                Write-Host "   - On Windows: .\advanced-cleanup.ps1"
                Write-Host "   - On macOS/Linux: ./advanced-cleanup.sh"
                $script:issuesFound = $true
            } else {
                Write-Host "✓ No TileTemplate references found"
            }
        } else {
            Write-Host "✓ Package appears correct (no AutoTileTemplate.cs found as expected)"
        }
    } else {
        Write-Host "⚠️  tilemap.extras not found in PackageCache"
        Write-Host "   Unity hasn't downloaded packages yet"
        Write-Host "   Solution: Open project in Unity to download packages"
    }
} else {
    Write-Host "ℹ Library\PackageCache does not exist"
    Write-Host "   This is normal for a fresh clone"
    Write-Host "   Unity will create it when you open the project"
}

# Summary
Write-Host ""
Write-Host "[5/5] Summary and Recommendations"
Write-Host "=========================================="

# Determine if there are issues
$issuesFound = $false

if (Test-Path $packageCachePath) {
    $cachedPackage = Get-ChildItem $packageCachePath -Directory -Filter "com.unity.2d.tilemap.extras@*" -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($cachedPackage) {
        $autoTilePath = Join-Path $cachedPackage.FullName "Editor\Tiles\AutoTile\AutoTileTemplate.cs"
        if (Test-Path $autoTilePath) {
            $fileContent = Get-Content $autoTilePath -Raw -ErrorAction SilentlyContinue
            if ($fileContent -match "TileTemplate") {
                $issuesFound = $true
            }
        }
    }
}

if ($issuesFound) {
    Write-Host "❌ ISSUES DETECTED"
    Write-Host ""
    Write-Host "Your Unity package cache contains old, incompatible files."
    Write-Host "This is causing the TileTemplate compilation errors."
    Write-Host ""
    Write-Host "Recommended action:"
    Write-Host "  1. Close Unity completely"
    Write-Host "  2. Run the advanced cleanup script:"
    Write-Host "     - Windows: .\advanced-cleanup.ps1"
    Write-Host "     - macOS/Linux: ./advanced-cleanup.sh"
    Write-Host "  3. Reopen the project in Unity"
    Write-Host ""
} else {
    Write-Host "✓ NO ISSUES DETECTED"
    Write-Host ""
    Write-Host "Package configuration appears correct."
    Write-Host ""
    $libraryPath = Join-Path $ProjectDir "Library"
    if (-not (Test-Path $libraryPath)) {
        Write-Host "Next step: Open the project in Unity to generate the Library folder"
    } else {
        Write-Host "If you're still experiencing errors:"
        Write-Host "  1. Check the Unity Console for specific error messages"
        Write-Host "  2. Try running the advanced-cleanup script"
        Write-Host "  3. See TROUBLESHOOTING.md for more solutions"
    }
}

Write-Host ""
